CREATE TABLE RESERVATIONS(
  RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ROOM_ID BIGINT NOT NULL,
  GUEST_ID BIGINT NOT NULL,
  RES_DATE DATE
);

CREATE INDEX res_guest_idx on RESERVATIONS(GUEST_ID);
CREATE INDEX res_date_idx on RESERVATIONS(RES_DATE)